@url=http://localhost:5000/api
@json=Content-Type: application/json

### 登录
post {{url}}/login
{{json}}

{
    "username": "yuwjoo6",
    "password": "1234567"
}
### 注册
post {{url}}/register
{{json}}

{
    "username": "yuwjoo6",
    "password": "1234567",
    "sex": "女",
    "email": "1191759350@qq.com",
    "phone": "17136375393",
    "SID": "201803605113",
    "nickname": "牧田"
}
### 所有用户
get {{url}}/users

### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOWM1YWQ3ODljNTZmMjkzNDlhYzhjOCIsImlhdCI6MTU4ODA4MDMzOCwiZXhwIjoxNTg4MDgzOTM4fQ.BejdF3xVh3BG2oSKzMulyoaO_XFvTCpjGfdLMUwgo3w

### 班级信息
POST {{url}}/classes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOWM1YWQ3ODljNTZmMjkzNDlhYzhjOCIsImlhdCI6MTU4ODE1NDE1MywiZXhwIjoxNTg4MTU3NzUzfQ.zeavi8QoIYB0vCXOsLJgyeIIG2kxEP32PN0mmw3A9mQ
{{json}}

{
    "class": "18移动互联网应用技术高技班"
}

### 追加资产记录
POST {{url}}/pushMoneyMessage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOWM1YWQ3ODljNTZmMjkzNDlhYzhjOCIsImlhdCI6MTU4ODE1NDE1MywiZXhwIjoxNTg4MTU3NzUzfQ.zeavi8QoIYB0vCXOsLJgyeIIG2kxEP32PN0mmw3A9mQ
{{json}}

{ 
    "class": "18移动互联网应用技术高技班",
    "content": "班级支出10元",
    "detail": "",
    "timestamp": "2020-4-5 12:53:21",
    "type": "1"
}